In [1]:
from sklearn import preprocessing
import pandas as pd

In [2]:
df = pd.read_csv("performance.csv")

In [3]:
df.head()

Name  GamesPlayed  MinutesPlayed  PointsPerGame  FieldGoalsMade  \
0   Brandon Ingram           36           27.4            7.4             2.6   
1  Andrew Harrison           35           26.9            7.2             2.0   
2   JaKarr Sampson           74           15.3            5.2             2.0   
3      Malik Sealy           58           11.6            5.7             2.3   
4      Matt Geiger           48           11.5            4.5             1.6   

   FieldGoalsAttempt  FieldGoalPercent  3PointMade  3PointAttempt  \
0                7.6              34.7         0.5            2.1   
1                6.7              29.6         0.7            2.8   
2                4.7              42.2         0.4            1.7   
3                5.5              42.6         0.1            0.5   
4                3.0              52.4         0.0            0.1   

   3PointPercent  ...  FreeThrowAttempt  FreeThrowPercent  OffensiveRebounds  \
0           25.0  ...               2.3              69.9                0.7   
1           23.5  ...               3.4              76.5                0.5   
2           24.4  ...               1.3              67.0                0.5   
3           22.6  ...               1.3              68.9                1.0   
4            0.0  ...               1.9              67.4                1.0   

   DefensiveRebounds  Rebounds  Assists  Steals  Blocks  Turnovers  Target  
0                3.4       4.1      1.9     0.4     0.4        1.3       0  
1                2.0       2.4      3.7     1.1     0.5        1.6       0  
2                1.7       2.2      1.0     0.5     0.3        1.0       0  
3                0.9       1.9      0.8     0.6     0.1        1.0       1  
4                1.5       2.5      0.3     0.3     0.4        0.8       1  

[5 rows x 21 columns]

## Label Encoder
Permite convertir los valores de tipo object a valores numéricos

In [4]:
len(df.Name)

1340

In [5]:
# Primer paso: Instanciar el Encoder
encoder = preprocessing.LabelEncoder()

In [6]:
# 2do paso: Entrenar el encoder
encoder.fit(df.Name)

LabelEncoder()

In [7]:
# Paso opcional
encoder.classes_

array(['A.C. Green', 'A.J. English', 'A.J. Price', ..., 'Xavier McDaniel',
       'Zach LaVine', 'Zach Randolph'], dtype=object)

In [8]:
# 3er paso: Transformar a valores numéricos
df.Name = encoder.transform(df.Name)

In [9]:
df.head()

Name  GamesPlayed  MinutesPlayed  PointsPerGame  FieldGoalsMade  \
0   128           36           27.4            7.4             2.6   
1    45           35           26.9            7.2             2.0   
2   521           74           15.3            5.2             2.0   
3   820           58           11.6            5.7             2.3   
4   871           48           11.5            4.5             1.6   

   FieldGoalsAttempt  FieldGoalPercent  3PointMade  3PointAttempt  \
0                7.6              34.7         0.5            2.1   
1                6.7              29.6         0.7            2.8   
2                4.7              42.2         0.4            1.7   
3                5.5              42.6         0.1            0.5   
4                3.0              52.4         0.0            0.1   

   3PointPercent  ...  FreeThrowAttempt  FreeThrowPercent  OffensiveRebounds  \
0           25.0  ...               2.3              69.9                0.7   
1           23.5  ...               3.4              76.5                0.5   
2           24.4  ...               1.3              67.0                0.5   
3           22.6  ...               1.3              68.9                1.0   
4            0.0  ...               1.9              67.4                1.0   

   DefensiveRebounds  Rebounds  Assists  Steals  Blocks  Turnovers  Target  
0                3.4       4.1      1.9     0.4     0.4        1.3       0  
1                2.0       2.4      3.7     1.1     0.5        1.6       0  
2                1.7       2.2      1.0     0.5     0.3        1.0       0  
3                0.9       1.9      0.8     0.6     0.1        1.0       1  
4                1.5       2.5      0.3     0.3     0.4        0.8       1  

[5 rows x 21 columns]

In [10]:
# Retorna los valores numéricos a las clases (obj)
inverse = encoder.inverse_transform(df.Name)

In [11]:
inverse

array(['Brandon Ingram', 'Andrew Harrison', 'JaKarr Sampson', ...,
       'Marlon Maxey', 'Litterial Green', 'Jon Barry'], dtype=object)

In [12]:
# Entrena y transforma las clases a valores numéricos
fit_transformed = encoder.fit_transform(inverse)

In [13]:
fit_transformed

array([128,  45, 521, ..., 855, 795, 644])

## Proceso de estandarización -  StandarScaler
Este algoritmo sigue la fórmula de la distribución estándar  Z = (x  - m) / sd

In [14]:
# 1er. paso: Inicializar el scaler
scaler = preprocessing.StandardScaler()

In [15]:
# 2do. paso: Entrenar el Scaler
scaler.fit(df.GamesPlayed.to_numpy().reshape(-1, 1))

StandardScaler()

In [16]:
# Paso Opcional: Conocer la media (o medias)
scaler.mean_

array([60.4141791])

In [17]:
scaler.scale_

array([17.42748581])

In [18]:
# 3er. paso: Transfomar los valores originales a la nueva escala
standardized = scaler.transform(df.GamesPlayed.to_numpy().reshape(-1, 1))

In [19]:
standardized

array([[-1.40090082],
       [-1.45828144],
       [ 0.77956287],
       ...,
       [-0.99923645],
       [-0.48281084],
       [-0.76971396]])

In [20]:
multiple_scaler = preprocessing.StandardScaler()
dummy_test = multiple_scaler.fit_transform([df.GamesPlayed, df.FieldGoalsMade])

In [21]:
dummy_test[0]

array([1., 1., 1., ..., 1., 1., 1.])

## Proceso de Estandarización - MinMaxScaler
Se basa en encontrar el valor de X standard bajo la siguiente fórmula

 x_std = ((x - x_min(axis=0)) / x.max(axis=0) - x.min(axis=0))
 
 x_scales = x_std * (max - min) + min 

In [22]:
# 1er paso: Inicialización del Scaler
min_max = preprocessing.MinMaxScaler()

In [23]:
# 2do. paso: Entrenamos el Scaler
min_max.fit(df.GamesPlayed.to_numpy().reshape(-1, 1))

MinMaxScaler()

In [24]:
# Paso Opcional: Revisar los valores mínimos y máximos
min_max.min_

array([-0.15492958])

In [25]:
# 3er.Paso: Se transforma los valores a la nueva escala
minimized = min_max.transform(df.GamesPlayed.to_numpy().reshape(-1, 1))

In [26]:
minimized

array([[0.35211268],
       [0.33802817],
       [0.88732394],
       ...,
       [0.45070423],
       [0.57746479],
       [0.50704225]])

## Proceso de Estandarización - MaxAbsScaler

In [27]:
# 1er paso Inicializar el Scaler
max_abs = preprocessing.MaxAbsScaler()

In [29]:
# 2do Paso - Entrenar el Scaler
max_abs.fit([df.GamesPlayed, df.PointsPerGame])

MaxAbsScaler()

In [30]:
# Paso opcional. Evaluar los valores máximo absoluto
max_abs.max_abs_

array([36., 35., 74., ..., 43., 52., 47.])

In [31]:
# 3er. Paso Aplicar el transform
abs_scaled = max_abs.transform([df.GamesPlayed, df.PointsPerGame])

In [32]:
abs_scaled

array([[1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [0.20555556, 0.20571429, 0.07027027, ..., 0.1255814 , 0.08653846,
        0.09361702]])

## Normalización - Normalize

In [35]:
# 1er. Paso / Llamamos al método normalize para ajustar los valores
normal = preprocessing.normalize([df.GamesPlayed, df.PointsPerGame])

In [36]:
# Evaluamos la data generada
normal

array([[0.01564063, 0.01520617, 0.03215019, ..., 0.01868186, 0.02259202,
        0.02041971],
       [0.02502887, 0.02435241, 0.01758785, ..., 0.01826431, 0.01522026,
        0.01488203]])

In [37]:
#pre = preprocessing.Normalizer()
#pre.fit

## Discretización - K-bins Disccretization

In [38]:
# 1er. Paso - Inicializamos el discretizador
k_bins = preprocessing.KBinsDiscretizer()

In [39]:
k_bins.fit([df.GamesPlayed, df.PointsPerGame])

KBinsDiscretizer()

In [40]:
k_bins.bin_edges_

array([array([ 7.4 , 13.12, 18.84, 24.56, 30.28, 36.  ]),
       array([ 7.2 , 12.76, 18.32, 23.88, 29.44, 35.  ]),
       array([ 5.2 , 18.96, 32.72, 46.48, 60.24, 74.  ]), ...,
       array([ 5.4 , 12.92, 20.44, 27.96, 35.48, 43.  ]),
       array([ 4.5, 14. , 23.5, 33. , 42.5, 52. ]),
       array([ 4.4 , 12.92, 21.44, 29.96, 38.48, 47.  ])], dtype=object)

In [41]:
discrete = k_bins.transform([df.GamesPlayed, df.PointsPerGame])

In [42]:
discrete

<2x6700 sparse matrix of type '<class 'numpy.float64'>'
	with 2680 stored elements in Compressed Sparse Row format>

In [45]:
x1, x2 = discrete.nonzero()

In [46]:
x1

array([0, 0, 0, ..., 1, 1, 1])

In [47]:
x2

array([   4,    9,   14, ..., 6685, 6690, 6695])